// HTML string for controlling MKZ4 from smartphone
String form =
    "<html>"
    "<head>"
    "<meta name='viewport' content='width=device-width, initial-scale=1, "
    "minimum-scale=1, maximum-scale=1'>"
    "<title>MKZ4 Controller</title>"
    "<style type='text/css'>"
    "* { margin: 0; padding: 0; }"
    "body { background-color: #0097c1; }"
    ".value {"
    "position: fixed;"
    "width: 100%;"
    "top: 50px;"
    "text-align: center;"
    "color: white;"
    "font-family: sans-serif;"
    "font-size: 200%;"
    "font-weight: normal;"
    "text-transform: capitalize;"
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div id='value' class='value'>connected</div>"
    "<form id='form' action='' target='tif'>"
    "<iframe src='javascript: false;' style='display: none' name='tif' "
    "id='tif'></iframe>"
    "</form>"
    "<script type='text/javascript'>"
    "var offset = 50;"
    "document.body.style.height = document.body.clientHeight + offset + 'px';"
    "document.body.style.width = document.body.clientWidth + offset + 'px';"
    "document.getElementsByTagName('html')[0].style.height = "
    "document.body.style.height + 'px';"
    "document.getElementsByTagName('html')[0].style.width = "
    "document.body.style.width + 'px';"
    "var moveHomePosition = function () {"
    "document.body.scrollTop = offset / 2;"
    "document.body.scrollLeft = offset / 2;"
    "};"
    "setTimeout(moveHomePosition, 300);"
    "var startX = 0;"
    "var startY = 0;"
    "var command = '/stop';"
    "var threshold = 40;"
    "var esp_port = 'http://192.168.4.1:8080';"
    "var el_form = document.getElementById('form');"
    "document.body.ontouchstart = function (event) {"
    "startX = event.touches[0].clientX;"
    "startY = event.touches[0].clientY;"
    "};"
    "document.body.ontouchmove = function (event) {"
    "var x = parseInt(event.touches[0].clientX - startX);"
    "var y = parseInt(event.touches[0].clientY - startY);"
    "var url = null;"
    "if (x < threshold * -1) {"
    "if (y < threshold * -1) {"
    "url = '/left FORWARD';"
    "} else if (y > threshold) {"
    "url = '/left back';"
    "} else {"
    "url = '/left';"
    "}"
    "} else if (x > threshold) {"
    "if (y < threshold * -1) {"
    "url = '/right FORWARD';"
    "} else if (y > threshold) {"
    "url = '/right back';"
    "} else {"
    "url = '/right';"
    "}"
    "} else {"
    "if (y < threshold * -1) {"
    "url = '/FORWARD';"
    "} else if (y > threshold) {"
    "url = '/back';"
    "}"
    "}"
    "if (command != url && url) {"
    "el_form.action = esp_port + url.replace(/<br>| /, '');"
    "el_form.submit();"
    "document.getElementById('value').innerHTML = url.replace(/\\//, '');"
    "}"
    "command = url;"
    "};"
    "document.body.ontouchend = function (event) {"
    "el_form.action = esp_port + '/stop';"
    "el_form.submit();"
    "setTimeout(moveHomePosition, 50);"
    "document.getElementById('value').innerHTML = 'stop';"
    "};"
    "</script>"
    "</body>"
    "</html>";